name: Latest blog post workflow
on:
  schedule: # Run workflow automatically
    - cron: '0 0 */10 * *' # Runs Every 1st, 11th, 21st and 31st of the month
  workflow_dispatch: # Run workflow manually (without waiting for the cron to be called), through the Github Actions Workflow page directly

jobs:
  update-readme-with-blog:
    name: Update this repo's README with latest blog posts
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Pull in dev.to posts
        uses: gautamkrishnar/blog-post-workflow@master
        with:
          feed_list: "https://medium.com/feed/@nullbyte"
          max_post_count: 7
          commit_message: "Updated latest medium posts"
